# Generated by Django 5.0.1 on 2024-01-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
    ]
