# Generated by Django 5.0.1 on 2024-01-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
