# Generated by Django 5.0.1 on 2024-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='Sales',
            field=models.BooleanField(default=False),
        ),
    ]
