# Generated by Django 5.0.1 on 2024-01-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_photos_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='gender',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
