# Generated by Django 5.0.1 on 2024-01-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_photos_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
